name: droplink_mobile
description: Free local AirDrop-like file sharing for Android and Windows.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  file_picker: ^8.1.7
  http_parser: ^4.0.2
  mime: ^1.0.6
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
